### ISSUE TITLE
Attempting to retrieve details on some DOI's throws 500

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#319]
Example URL https://api.test.datacite.org/dois?detail=True&query=10.5438%2F6brg-2m37

Error returned is a generic ArgumentError

```
web_1            | App 960 output: ArgumentError - key cannot be blank:
web_1            | App 960 output:   app/controllers/dois_controller.rb:202:in `block (3 levels) in index'
web_1            | App 960 output:   app/controllers/dois_controller.rb:196:in `block (2 levels) in index'
web_1            | App 960 output:   app/controllers/dois_controller.rb:152:in `index'
web_1            | App 960 output:
```

Seems only this is generated on certain doi's originally found trying to query all of datacite's doi's, this specific DOI in the example was one i found that could also trigger it.

**Comment by richardhallett** [comment]
This is related to the has_many declaration on the doi_serializer.rb for media objects.
I believe it might be because it is expecting multiple records and therefore with only one response fails to parse correctly.

I spent a significant time attempting to debug this but the actual error seems to be hidden away in the rails serialisation and for the sake of simplicity I've decided it is just better to not attempt to add media relations when dealing with collections items, e.g. dois.

Separate to this I actually fixed the media relations to use correct UID when showing relations rather than the internal ID it was showing while investigating. See https://github.com/datacite/lupo/commit/9c1dee27ca9361453b4f4a8f199cc503e865c92a
