### ISSUE TITLE
API returns unpermitted paramter when sending just doi

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#357]
When attempting to make a API call e.g.
http --session=rph POST https://api.test.datacite.org/dois data:='{"data":{"type":"dois","attributes":{"doi":"10.70048/005882"}}}'

An unpermitted attribute exception is being thrown.
```

{
    "error": "Internal Server Error",
    "exception": "#<ActionController::UnpermittedParameters: found unpermitted parameter: :data>",
    "status": 500,
    "traces": {
        "Application Trace": [
            {
                "id": 2,
                "trace": "app/controllers/dois_controller.rb:578:in `safe_params'"
            },
            {
                "id": 3,
                "trace": "app/controllers/dois_controller.rb:296:in `create'"
            }
        ],
        "Framework Trace": [
            {
                "id": 0,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/strong_parameters.rb:872:in `unpermitted_parameters!'"
            },
            {
                "id": 1,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/strong_parameters.rb:540:in `permit'"
            },
            {
                "id": 4,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'"
            },
            {
                "id": 5,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'"
            },
            {
                "id": 6,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action'"
            },
            {
                "id": 7,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'"
            },
            {
                "id": 8,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'"
            },
            {
                "id": 9,
                "trace": "vendor/bundle/ruby/2.4.0/gems/audited-4.9.0/lib/audited/sweeper.rb:14:in `around'"
            },
            {
                "id": 10,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'"
            },
            {
                "id": 11,
                "trace": "vendor/bundle/ruby/2.4.0/gems/audited-4.9.0/lib/audited/sweeper.rb:14:in `around'"
            },
            {
                "id": 12,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'"
            },
            {
                "id": 13,
                "trace": "vendor/bundle/ruby/2.4.0/gems/sentry-raven-2.12.2/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'"
            },
            {
                "id": 14,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `instance_exec'"
            },
            {
                "id": 15,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'"
            },
            {
                "id": 16,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks'"
            },
            {
                "id": 17,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'"
            },
            {
                "id": 18,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'"
            },
            {
                "id": 19,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'"
            },
            {
                "id": 20,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'"
            },
            {
                "id": 21,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'"
            },
            {
                "id": 22,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'"
            },
            {
                "id": 23,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'"
            },
            {
                "id": 24,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'"
            },
            {
                "id": 25,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'"
            },
            {
                "id": 26,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'"
            },
            {
                "id": 27,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'"
            },
            {
                "id": 28,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'"
            },
            {
                "id": 29,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'"
            },
            {
                "id": 30,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'"
            },
            {
                "id": 31,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'"
            },
            {
                "id": 32,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'"
            },
            {
                "id": 33,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'"
            },
            {
                "id": 34,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'"
            },
            {
                "id": 35,
                "trace": "vendor/bundle/ruby/2.4.0/gems/turnout-2.5.0/lib/rack/turnout.rb:25:in `call'"
            },
            {
                "id": 36,
                "trace": "vendor/bundle/ruby/2.4.0/gems/flipper-0.16.2/lib/flipper/middleware/memoizer.rb:62:in `memoized_call'"
            },
            {
                "id": 37,
                "trace": "vendor/bundle/ruby/2.4.0/gems/flipper-0.16.2/lib/flipper/middleware/memoizer.rb:40:in `call'"
            },
            {
                "id": 38,
                "trace": "vendor/bundle/ruby/2.4.0/gems/batch-loader-1.4.1/lib/batch_loader/middleware.rb:11:in `call'"
            },
            {
                "id": 39,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/deflater.rb:34:in `call'"
            },
            {
                "id": 40,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'"
            },
            {
                "id": 41,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'"
            },
            {
                "id": 42,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'"
            },
            {
                "id": 43,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:559:in `call'"
            },
            {
                "id": 44,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'"
            },
            {
                "id": 45,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'"
            },
            {
                "id": 46,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'"
            },
            {
                "id": 47,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "id": 48,
                "trace": "vendor/bundle/ruby/2.4.0/gems/better_errors-2.5.1/lib/better_errors/middleware.rb:59:in `call'"
            },
            {
                "id": 49,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'"
            },
            {
                "id": 50,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"
            },
            {
                "id": 51,
                "trace": "vendor/bundle/ruby/2.4.0/gems/lograge-0.10.0/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'"
            },
            {
                "id": 52,
                "trace": "vendor/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'"
            },
            {
                "id": 53,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'"
            },
            {
                "id": 54,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'"
            },
            {
                "id": 55,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'"
            },
            {
                "id": 56,
                "trace": "vendor/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'"
            },
            {
                "id": 57,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"
            },
            {
                "id": 58,
                "trace": "vendor/bundle/ruby/2.4.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'"
            },
            {
                "id": 59,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'"
            },
            {
                "id": 60,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'"
            },
            {
                "id": 61,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"
            },
            {
                "id": 62,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "id": 63,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'"
            },
            {
                "id": 64,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'"
            },
            {
                "id": 65,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-utf8_sanitizer-1.6.0/lib/rack/utf8_sanitizer.rb:22:in `call'"
            },
            {
                "id": 66,
                "trace": "vendor/bundle/ruby/2.4.0/gems/sentry-raven-2.12.2/lib/raven/integrations/rack.rb:51:in `call'"
            },
            {
                "id": 67,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-cors-1.0.3/lib/rack/cors.rb:95:in `call'"
            },
            {
                "id": 68,
                "trace": "vendor/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'"
            },
            {
                "id": 69,
                "trace": "/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'"
            },
            {
                "id": 70,
                "trace": "/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'"
            },
            {
                "id": 71,
                "trace": "/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'"
            },
            {
                "id": 72,
                "trace": "/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'"
            },
            {
                "id": 73,
                "trace": "/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'"
            }
        ],
        "Full Trace": [
            {
                "id": 0,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/strong_parameters.rb:872:in `unpermitted_parameters!'"
            },
            {
                "id": 1,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/strong_parameters.rb:540:in `permit'"
            },
            {
                "id": 2,
                "trace": "app/controllers/dois_controller.rb:578:in `safe_params'"
            },
            {
                "id": 3,
                "trace": "app/controllers/dois_controller.rb:296:in `create'"
            },
            {
                "id": 4,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'"
            },
            {
                "id": 5,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'"
            },
            {
                "id": 6,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action'"
            },
            {
                "id": 7,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'"
            },
            {
                "id": 8,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'"
            },
            {
                "id": 9,
                "trace": "vendor/bundle/ruby/2.4.0/gems/audited-4.9.0/lib/audited/sweeper.rb:14:in `around'"
            },
            {
                "id": 10,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'"
            },
            {
                "id": 11,
                "trace": "vendor/bundle/ruby/2.4.0/gems/audited-4.9.0/lib/audited/sweeper.rb:14:in `around'"
            },
            {
                "id": 12,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'"
            },
            {
                "id": 13,
                "trace": "vendor/bundle/ruby/2.4.0/gems/sentry-raven-2.12.2/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'"
            },
            {
                "id": 14,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `instance_exec'"
            },
            {
                "id": 15,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'"
            },
            {
                "id": 16,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks'"
            },
            {
                "id": 17,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'"
            },
            {
                "id": 18,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'"
            },
            {
                "id": 19,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'"
            },
            {
                "id": 20,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'"
            },
            {
                "id": 21,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'"
            },
            {
                "id": 22,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'"
            },
            {
                "id": 23,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'"
            },
            {
                "id": 24,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'"
            },
            {
                "id": 25,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'"
            },
            {
                "id": 26,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'"
            },
            {
                "id": 27,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'"
            },
            {
                "id": 28,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'"
            },
            {
                "id": 29,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'"
            },
            {
                "id": 30,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'"
            },
            {
                "id": 31,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'"
            },
            {
                "id": 32,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'"
            },
            {
                "id": 33,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'"
            },
            {
                "id": 34,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'"
            },
            {
                "id": 35,
                "trace": "vendor/bundle/ruby/2.4.0/gems/turnout-2.5.0/lib/rack/turnout.rb:25:in `call'"
            },
            {
                "id": 36,
                "trace": "vendor/bundle/ruby/2.4.0/gems/flipper-0.16.2/lib/flipper/middleware/memoizer.rb:62:in `memoized_call'"
            },
            {
                "id": 37,
                "trace": "vendor/bundle/ruby/2.4.0/gems/flipper-0.16.2/lib/flipper/middleware/memoizer.rb:40:in `call'"
            },
            {
                "id": 38,
                "trace": "vendor/bundle/ruby/2.4.0/gems/batch-loader-1.4.1/lib/batch_loader/middleware.rb:11:in `call'"
            },
            {
                "id": 39,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/deflater.rb:34:in `call'"
            },
            {
                "id": 40,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'"
            },
            {
                "id": 41,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'"
            },
            {
                "id": 42,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'"
            },
            {
                "id": 43,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:559:in `call'"
            },
            {
                "id": 44,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'"
            },
            {
                "id": 45,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'"
            },
            {
                "id": 46,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'"
            },
            {
                "id": 47,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "id": 48,
                "trace": "vendor/bundle/ruby/2.4.0/gems/better_errors-2.5.1/lib/better_errors/middleware.rb:59:in `call'"
            },
            {
                "id": 49,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'"
            },
            {
                "id": 50,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"
            },
            {
                "id": 51,
                "trace": "vendor/bundle/ruby/2.4.0/gems/lograge-0.10.0/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'"
            },
            {
                "id": 52,
                "trace": "vendor/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'"
            },
            {
                "id": 53,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'"
            },
            {
                "id": 54,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'"
            },
            {
                "id": 55,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'"
            },
            {
                "id": 56,
                "trace": "vendor/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'"
            },
            {
                "id": 57,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"
            },
            {
                "id": 58,
                "trace": "vendor/bundle/ruby/2.4.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'"
            },
            {
                "id": 59,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'"
            },
            {
                "id": 60,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'"
            },
            {
                "id": 61,
                "trace": "vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"
            },
            {
                "id": 62,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "id": 63,
                "trace": "vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'"
            },
            {
                "id": 64,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'"
            },
            {
                "id": 65,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-utf8_sanitizer-1.6.0/lib/rack/utf8_sanitizer.rb:22:in `call'"
            },
            {
                "id": 66,
                "trace": "vendor/bundle/ruby/2.4.0/gems/sentry-raven-2.12.2/lib/raven/integrations/rack.rb:51:in `call'"
            },
            {
                "id": 67,
                "trace": "vendor/bundle/ruby/2.4.0/gems/rack-cors-1.0.3/lib/rack/cors.rb:95:in `call'"
            },
            {
                "id": 68,
                "trace": "vendor/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'"
            },
            {
                "id": 69,
                "trace": "/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'"
            },
            {
                "id": 70,
                "trace": "/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'"
            },
            {
                "id": 71,
                "trace": "/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'"
            },
            {
                "id": 72,
                "trace": "/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'"
            },
            {
                "id": 73,
                "trace": "/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'"
            }
        ]
    }
}

```

**Comment by richardhallett** [comment]
Invalid test, wrong http call.
